title: ふんわり予想
description: Gemini AIが自動生成したふんわりと明日を予想するシステム
# theme: minima # オプション: 人気のあるJekyllテーマ。最初はコメントアウトしておき、後で有効にできます。
timezone: "Asia/Tokyo"

# _postsフォルダ内のMarkdownファイルにデフォルトでpostレイアウトを適用
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
# ... (title, description などの設定) ...
baseurl: "/Funwariyoso" # あなたのリポジトリ名に合わせてスラッシュから記述
# ...
